update post-commit

diff --git a/post-commit b/post-commit
--- a/post-commit
+++ b/post-commit
@@ -3,7 +3,7 @@
 export LOG="/gitit/logs/git.log"
 
 die () {
-    echo "$1" 
+    echo "$1"
     exit 1
 }
 
@@ -12,15 +12,12 @@ date >> $LOG
 
 eval $(ssh-agent) >> $LOG 2>&1 || die "SSH agent failed"
 
-git fetch origin master >> $LOG 2>&1 || die "Fetch failed" 
+git fetch origin master >> $LOG 2>&1 || die "Fetch failed"
 
 git merge --no-ff --no-edit origin master >> $LOG 2>&1
 if git status | grep -q "Unmerged"
 then
-    echo "commiting"
     git commit -a -m "auto-merge" >> $LOG 2>&1 || die "Auto-merge commit failed"
-else
-    exit 2
 fi
 
 git push origin master >> $LOG 2>&1 || die "Push failed"
